### ISSUE TITLE
CSS variables may be minimified with default values

### ISSUE THREAD

**Issue by dascritch** [dascritch/cpu-audio#179]
by example ;

```
	--pl-bg  :  var(--cpu-playing-background, #444)
```

And so we don't need to inject a global.css in the main DOM

**Comment by dascritch** [comment]
Not really possible.
By example, [in the default theme, the global css](https://github.com/dascritch/cpu-audio/blob/master/src/themes/default/global.css#L31) uses breakpointed definitions : 

```css
@media (max-width: 480px) {
        :root , .interface {
                --cpu-elapse-width : 70px;
        }
}
```
