### ISSUE TITLE
Some css vars settings won't be useful

### ISSUE THREAD

**Issue by dascritch** [dascritch/cpu-audio#29]
Try those personnalization settings : 
```css
body {
	--cpu-background : transparent;
	--cpu-color : currentColor;
	--cpu-playing-background : transparent;
	--cpu-playing-color : currentColor;
}
```
When the mouse is over a link or button, the result is dirt, cannot be read.

Try to correct the issue if it's possible (filters ?), or document the impossibility.
