### ISSUE TITLE
Rework the graphic interface

### ISSUE THREAD

**Issue by dascritch** [dascritch/cpu-audio#58]
- [x] Add panel titles (comprehension, a11y)
 - [x] Timeline on the whole width under the buttons (ease to use on small width)

Feasible something like : 
```css
#pagemain {
     padding-bottom : 8px; /* make rooooooom ! those 8px is used below */
}

#line {
     position: absolute;
     left: calc(- var(--cpu-height));
     right: calc(- var(--cpu-height));
     height: 8px;
     top: 32px;
}
aside.borders {
     top : 0px
}
```
