### ISSUE TITLE
Use css contain to help browser perfs

### ISSUE THREAD

**Issue by dascritch** [dascritch/cpu-audio#85]
References :

 * https://developers.google.com/web/fundamentals/web-components/shadowdom
 * https://developer.mozilla.org/en-US/docs/Web/CSS/contain
 * https://developers.google.com/web/updates/2016/06/css-containment
 * https://termvader.github.io/css-contain/
 * https://blogs.igalia.com/mrego/2019/01/11/an-introduction-to-css-containment/

This should be suggestion for users for integrating web component.

Suggested in first link : 
```css
:host {
  display: block;
  contain: content; /* Boom. CSS containment FTW. */
}
```

also

```css
:host {
   all: initial; /* 1st rule so subsequent properties are reset. */
}
```
so we can remove reset styles (see https://developer.mozilla.org/fr/docs/Web/CSS/all )
