### ISSUE TITLE
Using touchstart event to emulate hover

### ISSUE THREAD

**Issue by dascritch** [dascritch/cpu-audio#9]
https://github.com/dascritch/ondemiroir-audio-tag/issues/37

something like ???

```css
.{{classname}} [title]:hover:after {
 display: block;
 position : absolute;
 top : -100%;
 content: attr(title);
 font-size:10px;
}
```
