### ISSUE TITLE
Swapping background and color should force opacity to 1

### ISSUE THREAD

**Issue by dascritch** [dascritch/cpu-audio#99]
Swapping background and color can be a mess when background opacity is 0. For accessibility reasons, we must extract the background color, and force its opacity to 1 before applying it as a color.

This is not a standard issue but an accessibility one.

And, yes, I know, i've blogged (partially) about it : <https://dascritch.net/post/2019/11/13/Deux-couleurs-bizarres-en-CSS>

**Comment by dascritch** [comment]
The main way is to seriously complexify it.

We can change definitions likethis : 
```css
a:hover, a:focus, button:hover, button:focus {
	color : var(--cpu-background);
	background : var(--cpu-color);
}
```
into this : 
```css
#interface{
	--invert-bg : var(--cpu-invert-background, var(--cpu-color))
	--invert-cl : var(--cpu-invert-color, var(--cpu-background))
}
/* ... */
a:hover, a:focus, button:hover, button:focus {
	color : var(--invert-bg);
	background : var(--invert-cl);
}
```

So, if the `--cpu-invert-background` and `--cpu-invert-color` properties aren't defined, we keep the original behaviour
